:scheduler:
  :dynamic: true
  :schedule:
    event_cleaner:
      every: ['1m', first_in: '1s']
      class: EventCleaner 
    tumblr_api:
      every: ['5m', first_in: '1s']
      class: TumblrApi 
