:scheduler:
  :dynamic: true
  :schedule:
    tumblr_api_init:
      every: ['20m', first_in: '1s']
      class: TumblrApiInit 
    tumblr_api_Update:
      every: ['10m', first_in: '1s']
      class: TumblrApiUpdate
